### PR TITLE
Add-alumni-and-edit-person

### PR DESCRIPTION
**Pull request by pv-gitjob**
Uses the hackernoon website, delete sqllite file to run

### CODE REVIEW

**Comment by pv-gitjob** [comment]
I guess you don't have to delete the whole sql file, just the superuser

**Comment by XZ7QN0** [comment]
Pulled this branch, and the only thing I noticed is that the `password` field is visible in plaintext in the `Admin` page. Haven't tested this anywhere else, but just thought that I'd share. Otherwise, these changes look fine. I can create an issue in the GitHub `issues` tracker for this so that we can be aware of this and attempt to fix this in a future `pull request`.

**Comment by XZ7QN0** [comment]
Let me know your thoughts, and I can go ahead and approve this change.

**Comment by pv-gitjob** [comment]
Changes need to be made to the admin file in accounts to hash the password and give it the requirements it would have otherwise.
What I got so far was, in accounts admin.py:
+ from django.contrib.auth.admin import UserAdmin
- class PersonAdmin(admin.ModelAdmin):
+ class PersonAdmin(UserAdmin):

this brings password back to the normal requirements like hashing, no common passwords and input it twice, but this doesn't show the other person/user fields in the admin page.

We can see what the others say or approve it and create an issue to alter accounts admin.py

**Pull request merged**
