### PR TITLE
Add-alumni-and-edit-person

### PR DESCRIPTION
**Pull request by pv-gitjob**
Thanks for the quick input Matt, altered "Person" model accordingly. Also changed the schedule fields from text to char, looks neater in the admin page.

### CODE REVIEW

**Comment by XZ7QN0** [comment]
For the `Person` model, there’s a few questions that I have: 

- Why is the `graduated` field an `IntegerField`? Is this in reference to the year that someone graduated?
- Is a `Person` object actually assigned to a `User` account? Or will it eventually override the `User` accounts?

**Comment by digitaluniverse** [comment]
The tutorial posted in slack is the type we should use

**Comment by pv-gitjob** [comment]
Yea I was thinking the graduated would just be a year. The slack tutorial has been giving me an error, but I'll tried to get that going if that is preferable

**Comment by digitaluniverse** [comment]
We can also go this route
https://auth0.com/docs/quickstart/backend/django/01-authorization

**Comment by pv-gitjob** [comment]
I got it running, I just had to delete the sqllite file

**Pull request closed without merging**
